$ErrorActionPreference = "Stop"
$path = "C:\Users\LENOVO\Desktop\cleancity2.1\docs\rapport\build_report.ps1"
$content = Get-Content -Raw -Path $path -Encoding UTF8

$map = @{
    "generale"="générale"; "generales"="générales"; "general"="général"; "generaux"="généraux";
    "donnees"="données"; "donnee"="donnée";
    "securite"="sécurité"; "securises"="sécurisés"; "securisation"="sécurisation"; "securiser"="sécuriser"; "securisee"="sécurisée";
    "dechets"="déchets"; "dechet"="déchet";
    "decharge"="décharge"; "decharges"="décharges";
    "problematique"="problématique"; "problemes"="problèmes"; "probleme"="problème";
    "acces"="accès";
    "regulier"="régulier"; "reguliere"="régulière"; "regulieres"="régulières"; "reguliers"="réguliers"; "regulierement"="régulièrement";
    "utilisees"="utilisées"; "utilisee"="utilisée"; "utilises"="utilisés"; "utilise"="utilisé"; "utiliser"="utiliser";
    "numerique"="numérique"; "numeriques"="numériques"; "numeriquement"="numériquement";
    "geolocalisation"="géolocalisation"; "geolocalise"="géolocalisé"; "geolocalisee"="géolocalisée"; "geolocalises"="géolocalisés"; "geolocalisees"="géolocalisées"; "geolocalisant"="géolocalisant";
    "geographique"="géographique"; "geographiques"="géographiques"; "geographie"="géographie";
    "geospatial"="géospatial"; "geospatiale"="géospatiale"; "geospatiales"="géospatiales";
    "geospatiaux"="géospatiaux";
    "preciser"="préciser"; "precise"="précise"; "precises"="précises"; "precisement"="précisément";
    "systeme"="système"; "systemes"="systèmes";
    "reference"="référence"; "references"="références"; "referencer"="référencer"; "referencee"="référencée"; "referencees"="référencées";
    "integree"="intégrée"; "integres"="intégrés"; "integration"="intégration"; "integrer"="intégrer"; "integrant"="intégrant"; "integrees"="intégrées";
    "derniere"="dernière"; "dernieres"="dernières";
    "premiere"="première"; "premieres"="premières";
    "realite"="réalité";
    "specifique"="spécifique"; "specifiques"="spécifiques"; "specifications"="spécifications"; "specification"="spécification"; "specifiquement"="spécifiquement"; "specifiee"="spécifiée";
    "etudes"="études"; "etude"="étude"; "etudiant"="étudiant";
    "academique"="académique"; "academiques"="académiques"; "academie"="académie";
    "annee"="année"; "annees"="années";
    "periode"="période"; "periodes"="périodes";
    "delai"="délai"; "delais"="délais";
    "degradee"="dégradée"; "degradees"="dégradées"; "degrade"="dégradé";
    "necessaire"="nécessaire"; "necessaires"="nécessaires"; "necessite"="nécessite"; "necessitent"="nécessitent"; "necessitant"="nécessitant"; "necessitera"="nécessitera";
    "evenement"="événement"; "evenements"="événements";
    "evolutions"="évolutions"; "evoluer"="évoluer";
    "operateur"="opérateur"; "operateurs"="opérateurs"; "operation"="opération"; "operations"="opérations"; "operationnelle"="opérationnelle";
    "strategie"="stratégie"; "strategies"="stratégies";
    "economie"="économie"; "economique"="économique"; "economiques"="économiques";
    "ecologiques"="écologiques"; "ecologique"="écologique";
    "entierement"="entièrement"; "entiere"="entière"; "entieres"="entières";
    "reseau"="réseau"; "reseaux"="réseaux";
    "egalement"="également";
    "elevee"="élevée"; "eleve"="élevé"; "elevees"="élevées";
    "complementaire"="complémentaire"; "complementaires"="complémentaires";
    "completes"="complètes"; "completer"="compléter";
    "reponse"="réponse"; "reponses"="réponses";
    "redaction"="rédaction"; "redige"="rédigé"; "redigee"="rédigée";
    "presentes"="présentés"; "presentees"="présentées"; "presenter"="présenter"; "presentation"="présentation"; "presence"="présence";
    "metier"="métier";
    "methode"="méthode"; "methodologique"="méthodologique"; "methodes"="méthodes";
    "peripheries"="périphéries";
    "phenomene"="phénomène";
    "recuperables"="récupérables"; "recuperation"="récupération"; "recuperer"="récupérer"; "recuperees"="récupérées";
    "recurrente"="récurrente"; "recurrentes"="récurrentes";
    "reelle"="réelle"; "reels"="réels"; "reel"="réel"; "reellement"="réellement"; "reelles"="réelles";
    "realise"="réalisé"; "realisee"="réalisée"; "realisees"="réalisées"; "realises"="réalisés"; "realiser"="réaliser"; "realisation"="réalisation";
    "genere"="généré"; "generee"="générée"; "generes"="générés"; "generees"="générées"; "generer"="générer";
    "genie"="génie";
    "generateur"="générateur"; "generateurs"="générateurs"; "generatrice"="génératrice";
    "gerer"="gérer"; "gerees"="gérées"; "geres"="gérés"; "geree"="gérée";
    "cle"="clé"; "cles"="clés";
    "depot"="dépôt"; "depots"="dépôts";
    "dependance"="dépendance"; "dependances"="dépendances";
    "decideurs"="décideurs";
    "declenche"="déclenche"; "declenchee"="déclenchée"; "declencher"="déclencher"; "declenchement"="déclenchement"; "declencheur"="déclencheur"; "declenchant"="déclenchant"; "declenches"="déclenchés";
    "definit"="définit"; "definie"="définie"; "definies"="définies"; "definis"="définis"; "definir"="définir"; "definition"="définition";
    "delegataires"="délégataires";
    "demontrer"="démontrer"; "demontre"="démontre";
    "demarche"="démarche";
    "demarrage"="démarrage";
    "developpee"="développée"; "developpees"="développées"; "developpe"="développé"; "developpes"="développés"; "developpement"="développement"; "developper"="développer";
    "differents"="différents"; "differentes"="différentes"; "differenciees"="différenciées"; "difference"="différence"; "differences"="différences";
    "documentee"="documentée"; "documentees"="documentées";
    "echange"="échange"; "echanges"="échanges";
    "echelle"="échelle";
    "ecran"="écran"; "ecrans"="écrans";
    "ecrit"="écrit"; "ecrite"="écrite"; "ecrits"="écrits"; "ecrites"="écrites"; "ecriture"="écriture";
    "ecoulement"="écoulement";
    "effectuee"="effectuée"; "effectuees"="effectuées";
    "egard"="égard";
    "elaboration"="élaboration"; "elaboree"="élaborée"; "elabores"="élaborés";
    "elements"="éléments"; "element"="élément";
    "emis"="émis"; "emise"="émise"; "emises"="émises";
    "empeche"="empêche"; "empecher"="empêcher"; "empechant"="empêchant"; "empechee"="empêchée";
    "equipe"="équipe"; "equipes"="équipes"; "equipees"="équipées"; "equipee"="équipée";
    "etabli"="établi"; "etablissement"="établissement"; "etablissements"="établissements";
    "etendre"="étendre";
    "evaluer"="évaluer"; "evaluation"="évaluation"; "evaluee"="évaluée";
    "eventuelle"="éventuelle"; "eventuellement"="éventuellement"; "eventuelles"="éventuelles";
    "fonctionnalites"="fonctionnalités"; "fonctionnalite"="fonctionnalité";
    "grace"="grâce";
    "prealable"="préalable"; "prealablement"="préalablement";
    "prealables"="préalables";
    "immediat"="immédiat"; "immediate"="immédiate"; "immediatement"="immédiatement";
    "incendie"="incendie";
    "indexee"="indexée"; "indexees"="indexées";
    "inegalite"="inégalité";
    "installee"="installée";
    "integralement"="intégralement"; "integralite"="intégralité";
    "interet"="intérêt"; "interets"="intérêts";
    "isolee"="isolée";
    "legere"="légère"; "legeres"="légères"; "legerement"="légèrement";
    "liee"="liée"; "liees"="liées"; "lie"="lié"; "lies"="liés";
    "localisee"="localisée"; "localisees"="localisées";
    "manuelle"="manuelle"; "manuellement"="manuellement";
    "materielle"="matérielle"; "materiel"="matériel"; "materiaux"="matériaux";
    "maree"="marée";
    "mesure"="mesure"; "mesurable"="mesurable"; "mesurer"="mesurer";
    "methodologie"="méthodologie";
    "modelisation"="modélisation"; "modelise"="modélisé"; "modelisee"="modélisée";
    "moderee"="modérée";
    "multipliee"="multipliée";
    "necessairement"="nécessairement";
    "operee"="opérée"; "operees"="opérées";
    "orientee"="orientée"; "orientees"="orientées";
    "penetration"="pénétration";
    "performante"="performante"; "performantes"="performantes";
    "peripherique"="périphérique"; "peripheriques"="périphériques"; "peripherie"="périphérie";
    "phase"="phase";
    "preferee"="préférée"; "prefere"="préféré"; "preferes"="préférés"; "preference"="préférence"; "preferences"="préférences";
    "prevention"="prévention"; "prevenir"="prévenir"; "prevue"="prévue"; "prevu"="prévu"; "prevues"="prévues"; "prevus"="prévus"; "prevoir"="prévoir";
    "priorisation"="priorisation";
    "prioritaires"="prioritaires"; "prioritaire"="prioritaire";
    "procede"="procédé"; "procedes"="procédés"; "procedure"="procédure"; "procedures"="procédures";
    "protegee"="protégée"; "protege"="protégé"; "proteges"="protégés";
    "recente"="récente"; "recentes"="récentes"; "recemment"="récemment";
    "redondance"="redondance";
    "relevee"="relevée";
    "remuneration"="rémunération"; "remunerer"="rémunérer"; "remuneree"="rémunérée";
    "renforcee"="renforcée";
    "reparties"="réparties"; "reparti"="réparti";
    "repartition"="répartition";
    "repetee"="répétée";
    "repondre"="répondre"; "repond"="répond"; "repondent"="répondent";
    "resolue"="résolue"; "resoudre"="résoudre";
    "respectee"="respectée"; "respectees"="respectées";
    "responsabilite"="responsabilité"; "responsabilites"="responsabilités";
    "resultats"="résultats"; "resultat"="résultat";
    "resume"="résumé";
    "retenue"="retenue"; "retenues"="retenues";
    "reutilisation"="réutilisation";
    "revele"="révélé"; "revelee"="révélée";
    "selectionnee"="sélectionnée"; "selectionner"="sélectionner";
    "separation"="séparation"; "separee"="séparée"; "separees"="séparées";
    "serie"="série"; "series"="séries";
    "severite"="sévérité";
    "signaletique"="signalétique";
    "societe"="société";
    "specialisee"="spécialisée"; "specialisees"="spécialisées";
    "structuree"="structurée"; "structurees"="structurées";
    "successivement"="successivement";
    "supplementaire"="supplémentaire"; "supplementaires"="supplémentaires";
    "surete"="sûreté";
    "synthese"="synthèse";
    "tacherons"="tâcherons";
    "temoigne"="témoigne";
    "tracabilite"="traçabilité"; "tracables"="traçables"; "tracable"="traçable";
    "utilisateurs"="utilisateurs";
    "veritable"="véritable"; "veritablement"="véritablement";
    "vulnerabilite"="vulnérabilité"; "vulnerabilites"="vulnérabilités";
    "memoire"="mémoire";
    "reussi"="réussi";
    "sante"="santé";
    "etat"="état"; "etats"="états";
    "etape"="étape"; "etapes"="étapes";
    "efficacite"="efficacité";
    "specifie"="spécifié"; "specifiees"="spécifiées";
    "adaptee"="adaptée"; "adaptees"="adaptées"; "adapte"="adapté"; "adaptes"="adaptés";
    "associee"="associée"; "associees"="associées"; "associe"="associé"; "associes"="associés";
    "concernee"="concernée"; "concernees"="concernées"; "concerne"="concerné"; "concernes"="concernés";
    "creee"="créée"; "creees"="créées"; "cree"="créé"; "crees"="créés"; "creer"="créer"; "creation"="création";
    "declaree"="déclarée";
    "denomme"="dénommé";
    "designee"="désignée";
    "detaillee"="détaillée"; "detaillees"="détaillées"; "detaille"="détaillé"; "detailles"="détaillés"; "detailler"="détailler";
    "eleveee"="élevée";
    "engagee"="engagée";
    "estimee"="estimée";
    "generalise"="généralisé";
    "identifiee"="identifiée"; "identifiees"="identifiées"; "identifie"="identifié"; "identifies"="identifiés";
    "impliquee"="impliquée"; "impliquees"="impliquées"; "implique"="impliqué"; "impliques"="impliqués";
    "limitee"="limitée"; "limitees"="limitées"; "limite"="limité"; "limites"="limités";
    "localise"="localisé";
    "mesuree"="mesurée";
    "motivee"="motivée"; "motivees"="motivées";
    "obtenue"="obtenue";
    "organisee"="organisée"; "organisees"="organisées"; "organise"="organisé"; "organises"="organisés";
    "posee"="posée";
    "positionnee"="positionnée";
    "prevalue"="prévalue";
    "provisionne"="provisionné"; "provisionnee"="provisionnée";
    "reservee"="réservée"; "reservees"="réservées"; "reserve"="réservé"; "reserves"="réservés";
    "verrouillee"="verrouillée"; "verrouille"="verrouillé";
    "annexee"="annexée";
    "constituee"="constituée"; "constitue"="constitué"; "constitues"="constitués"; "constituees"="constituées";
    "constatee"="constatée";
    "controlee"="contrôlée"; "controlees"="contrôlées"; "controle"="contrôlé"; "controles"="contrôlés"; "controler"="contrôler";
    "convertibles"="convertibles";
    "affectee"="affectée"; "affectation"="affectation";
    "annexes"="annexes";
    "assumee"="assumée"; "assumees"="assumées";
    "bapteme"="baptême";
    "beneficier"="bénéficier"; "beneficiera"="bénéficiera";
    "capacite"="capacité"; "capacites"="capacités";
    "categorie"="catégorie"; "categories"="catégories";
    "circonscrit"="circonscrit";
    "coherence"="cohérence"; "coherent"="cohérent"; "coherente"="cohérente";
    "compatibilite"="compatibilité"; "compatible"="compatible";
    "completement"="complètement";
    "concue"="conçue"; "concu"="conçu"; "concus"="conçus"; "conçues"="conçues";
    "consideree"="considérée";
    "considerablement"="considérablement";
    "consommatrice"="consommatrice";
    "contrainte"="contrainte"; "contraintes"="contraintes";
    "coordonnee"="coordonnée"; "coordonnees"="coordonnées";
    "correspondance"="correspondance";
    "couverte"="couverte";
    "delimitee"="délimitée";
    "demographique"="démographique";
    "denombrer"="dénombrer";
    "deploiement"="déploiement"; "deployable"="déployable"; "deploye"="déployé"; "deployee"="déployée"; "deployees"="déployées"; "deployer"="déployer";
    "deroulement"="déroulement";
    "derives"="dérivés";
    "detecte"="détecté"; "detectee"="détectée";
    "determinant"="déterminant"; "determine"="détermine"; "determinee"="déterminée";
    "diagnostiquer"="diagnostiquer";
    "diminuee"="diminuée";
    "dispositif"="dispositif"; "dispositifs"="dispositifs";
    "documentation"="documentation";
    "domicilie"="domicilié";
    "ecoule"="écoulé";
    "efficace"="efficace";
    "emprunte"="emprunté";
    "encapsulee"="encapsulée";
    "enrichir"="enrichir"; "enrichie"="enrichie";
    "essentiellement"="essentiellement";
    "etendue"="étendue";
    "evite"="évite"; "eviter"="éviter"; "evitant"="évitant";
    "exclues"="exclues"; "exclu"="exclu";
    "execute"="exécuté"; "executee"="exécutée"; "executees"="exécutées"; "executer"="exécuter"; "execution"="exécution";
    "existante"="existante"; "existantes"="existantes";
    "exploration"="exploration";
    "exposees"="exposées"; "expose"="exposé";
    "fideles"="fidèles";
    "fournisseur"="fournisseur";
    "frequente"="fréquente"; "frequemment"="fréquemment";
    "generalement"="généralement";
    "genererait"="générerait";
    "guidee"="guidée";
    "heberge"="héberge"; "hebergement"="hébergement"; "hebergeur"="hébergeur"; "hebergees"="hébergées"; "heberges"="hébergés";
    "hierarchie"="hiérarchie";
    "impacte"="impacté";
    "implementation"="implémentation"; "implementer"="implémenter"; "implementee"="implémentée";
    "incoherence"="incohérence";
    "indeterminee"="indéterminée";
    "inspiree"="inspirée";
    "installe"="installé"; "installes"="installés";
    "integrale"="intégrale";
    "interessant"="intéressant";
    "interface"="interface";
    "interieur"="intérieur";
    "isolant"="isolant";
    "iteratif"="itératif"; "iterative"="itérative";
    "libere"="libéré";
    "localite"="localité";
    "logique"="logique";
    "mecanisme"="mécanisme"; "mecanismes"="mécanismes";
    "menagee"="ménagée";
    "meritent"="méritent"; "merite"="mérite";
    "modernite"="modernité";
    "mutualisee"="mutualisée"; "mutualise"="mutualisé";
    "necessairemnt"="nécessairement";
    "obtenir"="obtenir";
    "particulierement"="particulièrement"; "particuliere"="particulière"; "particulieres"="particulières"; "particulier"="particulier";
    "penalise"="pénalisé";
    "perenne"="pérenne";
    "persistee"="persistée";
    "personnalisation"="personnalisation"; "personnalisee"="personnalisée"; "personnalisees"="personnalisées"; "personnaliser"="personnaliser"; "personnalises"="personnalisés"; "personnalise"="personnalisé";
    "planifiee"="planifiée";
    "poursuivie"="poursuivie";
    "precede"="précède";
    "precoce"="précoce";
    "predefinie"="prédéfinie";
    "presuppose"="présuppose";
    "priviligie"="privilégié";
    "privilegiant"="privilégiant"; "privilegie"="privilégié"; "privileges"="privilèges"; "privilege"="privilège";
    "procure"="procure";
    "propagee"="propagée";
    "proposee"="proposée"; "proposees"="proposées"; "propose"="proposé"; "proposes"="proposés";
    "protegeant"="protégeant";
    "reagir"="réagir";
    "recevoir"="recevoir";
    "reciproque"="réciproque";
    "reglementaire"="réglementaire"; "reglementation"="réglementation";
    "regroupe"="regroupe"; "regroupant"="regroupant"; "regroupement"="regroupement";
    "rehaussee"="rehaussée";
    "relevant"="relevant";
    "renouvelable"="renouvelable";
    "repense"="repensé";
    "representant"="représentant"; "representative"="représentative"; "representatif"="représentatif"; "representation"="représentation";
    "requiert"="requiert";
    "resistance"="résistance";
    "responsable"="responsable";
    "reste"="reste";
    "retrouve"="retrouve";
    "reussie"="réussie"; "reussies"="réussies"; "reussis"="réussis";
    "revelateur"="révélateur";
    "scenarise"="scénarisé";
    "scenario"="scénario"; "scenarios"="scénarios";
    "securise"="sécurisé"; "securisees"="sécurisées"; "securisent"="sécurisent";
    "sensibilisation"="sensibilisation";
    "sequence"="séquence"; "sequences"="séquences"; "sequentielle"="séquentielle";
    "situee"="située"; "situees"="situées"; "situe"="situé";
    "societale"="sociétale";
    "specialement"="spécialement";
    "stimulee"="stimulée";
    "structurelle"="structurelle"; "structurel"="structurel";
    "suivie"="suivie"; "suivies"="suivies";
    "supposee"="supposée";
    "surexploitation"="surexploitation";
    "systematique"="systématique"; "systematiquement"="systématiquement";
    "temoignage"="témoignage";
    "tenue"="tenue";
    "theorique"="théorique"; "theoriques"="théoriques";
    "titre"="titre";
    "tolere"="toléré";
    "traitee"="traitée"; "traitees"="traitées"; "traite"="traité"; "traites"="traités";
    "transferee"="transférée"; "transferer"="transférer"; "transfert"="transfert";
    "transmise"="transmise"; "transmises"="transmises"; "transmis"="transmis";
    "unifiee"="unifiée";
    "utilitaires"="utilitaires";
    "validee"="validée"; "validees"="validées"; "valide"="validé"; "valides"="validés"; "validation"="validation";
    "valorisable"="valorisable"; "valorisables"="valorisables"; "valorisation"="valorisation"; "valorisee"="valorisée"; "valorise"="valorisé"; "valoriser"="valoriser";
    "variee"="variée"; "variees"="variées";
    "verifiee"="vérifiée"; "verifiees"="vérifiées"; "verifie"="vérifié"; "verifies"="vérifiés"; "verifier"="vérifier"; "verification"="vérification";
    "vise"="vise"; "visee"="visée"; "visees"="visées";
    "generation"="génération";
    "premiers"="premiers";
    "quatrieme"="quatrième"; "cinquieme"="cinquième"; "sixieme"="sixième"; "septieme"="septième"; "deuxieme"="deuxième"; "troisieme"="troisième";
    "civilite"="civilité";
    "actualisees"="actualisées"; "actualiser"="actualiser";
    "conges"="congés";
    "faciliterait"="faciliterait";
    "menagera"="ménagera";
    "recuperee"="récupérée";
    "regler"="régler";
    "revue"="revue";
    "temporaire"="temporaire";
    "utilite"="utilité";
    "decennies"="décennies"; "decennie"="décennie";
    "metropoles"="métropoles"; "metropole"="métropole";
    "connait"="connaît";
    "amenages"="aménagés"; "amenage"="aménagé"; "amenagee"="aménagée"; "amenagees"="aménagées"; "amenagement"="aménagement"; "amenagements"="aménagements";
    "documente"="documenté";
    "maniere"="manière"; "manieres"="manières";
    "negligeable"="négligeable"; "negligeables"="négligeables";
    "recuperent"="récupèrent"; "recupere"="récupère";
    "deficit"="déficit"; "deficits"="déficits";
    "etudiees"="étudiées"; "etudiee"="étudiée";
    "sourcees"="sourcées"; "sourcee"="sourcée";
    "modele"="modèle"; "modeles"="modèles";
    "lineaire"="linéaire"; "lineaires"="linéaires";
    "presente"="présente";
    "telephonique"="téléphonique"; "telephoniques"="téléphoniques"; "telephone"="téléphone";
    "consequences"="conséquences"; "consequence"="conséquence"; "consequent"="conséquent"; "consequente"="conséquente";
    "observees"="observées"; "observee"="observée";
    "centralises"="centralisés"; "centralisees"="centralisées"; "centralise"="centralisé";
    "defi"="défi"; "defis"="défis";
    "pretexte"="prétexte";
    "situes"="situés";
    "menagees"="ménagées";
    "occasionne"="occasionné"; "occasionnee"="occasionnée";
    "recurrent"="récurrent"; "recurrents"="récurrents";
    "role"="rôle"; "roles"="rôles";
    "regle"="règle"; "regles"="règles";
    "perimetre"="périmètre"; "perimetres"="périmètres";
    "francais"="français"; "francaise"="française"; "francaises"="françaises";
    "ete"="été";
    "evolution"="évolution";
    "menage"="ménage"; "menages"="ménages";
    "creneau"="créneau"; "creneaux"="créneaux";
    "ulterieure"="ultérieure"; "ulterieurement"="ultérieurement"; "ulterieures"="ultérieures"; "ulterieurs"="ultérieurs"; "ulterieur"="ultérieur";
    "enumere"="énuméré"; "enumeree"="énumérée"; "enumeres"="énumérés"
}

$sb = New-Object System.Text.StringBuilder
$evaluator = {
    param($m)
    $word = $m.Value
    $key = $word.ToLowerInvariant()
    if (-not $map.ContainsKey($key)) { return $word }
    $rep = $map[$key]
    if ($word -ceq $word.ToUpperInvariant() -and $word.Length -gt 1) {
        return $rep.ToUpperInvariant()
    } elseif ($word.Substring(0,1) -ceq $word.Substring(0,1).ToUpperInvariant()) {
        return $rep.Substring(0,1).ToUpperInvariant() + $rep.Substring(1)
    } else {
        return $rep
    }
}

foreach ($key in $map.Keys) {
    $pattern = '\b' + [regex]::Escape($key) + '\b'
    $content = [regex]::Replace($content, $pattern, $evaluator, [System.Text.RegularExpressions.RegexOptions]::IgnoreCase)
}

Set-Content -Path $path -Value $content -Encoding UTF8
Write-Output "ACCENTS_FIXED"


